"""Assemble a self-contained Markdown (or HTML) run report."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from quant_platform.config import AppConfig
from quant_platform.logging_utils import get_logger
from quant_platform.utils import ensure_dir

logger = get_logger(__name__)

_DISCLAIMER = (
    "> **Disclaimer.** This report is generated by an educational / portfolio "
    "research platform. It is **not financial advice** and **not intended for "
    "live trading**. Simulated/backtested performance has many well-known biases "
    "and does not guarantee future results."
)

_PCT_KEYS = {
    "cagr",
    "ann_return",
    "ann_volatility",
    "max_drawdown",
    "var_95",
    "cvar_95",
    "hit_rate",
    "alpha_ann",
    "avg_turnover",
    "annual_turnover",
    "best_day",
    "worst_day",
    "pct_positive_days",
    "avg_gross_exposure",
    "avg_net_exposure",
}


def _fmt(key: str, value: Any) -> str:
    if not isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, float) and (value != value):  # NaN
        return "n/a"
    if key in _PCT_KEYS:
        return f"{value * 100:.2f}%"
    return f"{value:.3f}"


def _metrics_table(metrics: dict[str, Any], *, headers=("Metric", "Value")) -> str:
    rows = [f"| {k} | {_fmt(k, v)} |" for k, v in metrics.items()]
    head = f"| {headers[0]} | {headers[1]} |\n|---|---|"
    return head + "\n" + "\n".join(rows)


def _compare_table(strat: dict[str, Any], bench: dict[str, Any], keys: list[str]) -> str:
    head = "| Metric | Strategy | Benchmark |\n|---|---|---|"
    rows = [f"| {k} | {_fmt(k, strat.get(k))} | {_fmt(k, bench.get(k))} |" for k in keys]
    return head + "\n" + "\n".join(rows)


def _df_to_md(df: pd.DataFrame, *, floatfmt: str = ".2%", index: bool = True) -> str:
    if df is None or df.empty:
        return "_(no data)_"
    try:
        from tabulate import tabulate

        return tabulate(df, headers="keys", tablefmt="github", floatfmt=floatfmt, showindex=index)
    except Exception:  # pragma: no cover - fallback
        return df.to_markdown(index=index)


def build_report(
    config: AppConfig,
    *,
    panel_meta: dict[str, Any],
    feature_names: list[str],
    train_result: Any,
    backtest_result: Any,
    risk_block: dict[str, Any],
    figures: dict[str, Path],
    output_path: Path,
    data_hash: str | None = None,
    git_commit: str | None = None,
) -> Path:
    """Render the full run report to ``output_path`` (Markdown)."""
    output_path = Path(output_path)
    ensure_dir(output_path.parent)
    fig_dir = config.report.figures_dir

    def fig_link(name: str) -> str:
        p = figures.get(name)
        if p is None:
            return ""
        rel = Path(p)
        try:
            rel = rel.relative_to(output_path.parent)
        except ValueError:
            rel = Path(fig_dir).name + "/" + rel.name
        return f"![{name}]({rel.as_posix()})\n"

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []
    a = lines.append

    a(f"# {config.report.title}\n")
    a(_DISCLAIMER + "\n")
    a("## 1. Run metadata\n")
    a(
        _metrics_table(
            {
                "Generated": now,
                "Config / experiment": config.project.name,
                "Random seed": config.project.seed,
                "Data source": panel_meta.get("source", "n/a"),
                "Dataset hash": data_hash or panel_meta.get("data_hash", "n/a"),
                "Git commit": git_commit or "n/a",
                "Model": f"{config.model.type} ({config.model.task})",
                "Strategy": f"{config.backtest.strategy} / {config.backtest.signal}",
            }
        )
        + "\n"
    )

    a("## 2. Data\n")
    a(
        _metrics_table(
            {
                "Tickers": ", ".join(panel_meta.get("tickers", [])),
                "Benchmark": config.data.benchmark,
                "Date range": f"{panel_meta.get('date_min')} → {panel_meta.get('date_max')}",
                "Observations": panel_meta.get("n_rows", "n/a"),
                "Price field": config.data.price_field,
            }
        )
        + "\n"
    )
    a(fig_link("price_history"))
    a(fig_link("correlation"))

    a("## 3. Features\n")
    a(f"- **{len(feature_names)}** features engineered per (date, ticker).\n")
    a(
        "- Families: returns, volatility/realised-vol, moving-average & EMA trend, "
        "RSI/MACD oscillators, Bollinger bands, momentum & 12-1 momentum, mean-reversion "
        "z-scores, volume features, rolling beta, drawdown features, and cross-sectional "
        "ranks/z-scores.\n"
    )
    a("<details><summary>Full feature list</summary>\n\n")
    a("\n".join(f"- `{f}`" for f in feature_names))
    a("\n\n</details>\n")

    a("## 4. Model performance (out-of-sample, walk-forward)\n")
    if train_result is not None:
        a(_metrics_table(train_result.metrics) + "\n")
        if train_result.fold_metrics:
            fold_df = pd.DataFrame(train_result.fold_metrics).set_index("fold")
            a("\n**Per-fold metrics**\n\n")
            a(_df_to_md(fold_df, floatfmt=".3f") + "\n")
        a(fig_link("feature_importance"))
        if config.model.task == "classification":
            a(fig_link("confusion_matrix"))
            a(fig_link("roc_curve"))
    else:
        a("_Rules-based baseline signal used; no ML model trained._\n")

    a("## 5. Backtest performance\n")
    bt = backtest_result
    compare_keys = [
        "cagr",
        "ann_volatility",
        "sharpe",
        "sortino",
        "calmar",
        "max_drawdown",
        "var_95",
        "cvar_95",
        "hit_rate",
        "beta",
    ]
    a(_compare_table(bt.stats, bt.benchmark_stats, compare_keys) + "\n")
    a("\n**Trading activity**\n\n")
    a(_metrics_table(bt.trade_summary) + "\n")
    a(fig_link("equity_curve"))
    a(fig_link("drawdown"))
    a(fig_link("rolling_sharpe"))
    a(fig_link("returns_distribution"))
    if not bt.monthly_returns.empty:
        a("\n**Monthly returns**\n\n")
        a(_df_to_md(bt.monthly_returns, floatfmt=".2%") + "\n")
        a(fig_link("monthly_returns"))

    a("## 6. Risk analytics\n")
    a(_metrics_table(risk_block.get("portfolio", {})) + "\n")
    stress = risk_block.get("stress")
    if stress is not None and len(stress):
        a("\n**Stress / scenario analysis**\n\n")
        a(_df_to_md(pd.DataFrame(stress), floatfmt=".2%", index=False) + "\n")

    a("## 7. Limitations\n")
    a(
        "- Daily close-to-close data only; no intraday, order-book, or borrow data.\n"
        "- Transaction costs/slippage are modelled as a flat per-turnover bps charge; "
        "real costs are size-, liquidity- and regime-dependent.\n"
        "- Survivorship bias: the universe is fixed and current; delisted names are absent.\n"
        "- Free data vendors may have adjustment/quality quirks vs. institutional feeds.\n"
        "- Single-config run; no hyper-parameter search or multiple-testing correction, "
        "so reported OOS edges should be treated cautiously.\n"
    )

    a("## 8. Future work\n")
    a(
        "- Intraday & alternative data; survivorship-bias-free universes.\n"
        "- Portfolio optimisation (mean-variance / risk-parity) and factor-risk models.\n"
        "- Hyper-parameter search with nested, purged cross-validation.\n"
        "- Event-driven backtester with realistic fills and capacity modelling.\n"
        "- Distributed backtesting and cloud orchestration.\n"
    )

    content = "\n".join(lines)
    if config.report.format == "html":
        content = _to_html(content, title=config.report.title)
        output_path = output_path.with_suffix(".html")

    output_path.write_text(content, encoding="utf-8")
    logger.info("Wrote report to %s", output_path)
    return output_path


def _to_html(markdown_text: str, *, title: str) -> str:
    """Best-effort Markdown→HTML; falls back to a <pre> block if no converter."""
    body: str
    try:  # pragma: no cover - optional dependency
        import markdown as md

        body = md.markdown(markdown_text, extensions=["tables", "fenced_code"])
    except Exception:
        import html

        body = f"<pre>{html.escape(markdown_text)}</pre>"
    return (
        "<!doctype html><html><head><meta charset='utf-8'>"
        f"<title>{title}</title>"
        "<style>body{font-family:system-ui,Arial,sans-serif;max-width:980px;"
        "margin:2rem auto;padding:0 1rem;line-height:1.5} "
        "table{border-collapse:collapse} td,th{border:1px solid #ccc;padding:4px 8px} "
        "img{max-width:100%}</style></head><body>"
        f"{body}</body></html>"
    )
